# Generated by Django 5.0.7 on 2024-07-13 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentCom', models.TextField(default='')),
                ('DatePosted', models.DateField()),
                ('postID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
            ],
        ),
    ]
